### ISSUE TITLE
Increase memory allowance for saves

### ISSUE THREAD

**Issue by jasonm23** [ijprest/keyboard-layout-editor#100]

**Comment by ijprest** [comment]
Yeah... I knew I needed to do this after adding the custom styles.  I've doubled the limit to 16kb.  Let's see how far that gets us.  

(I've got some ideas for a more-comprehensive storage solution... but they're not fully fleshed out yet.)

**Comment by jasonm23** [comment]
Good stuff

**Comment by jasonm23** [comment]
I don't suppose you'd consider allowing 32 or 48kb ?

**Comment by ijprest** [comment]
I just pushed my big storage change... I'm now using GitHub Gists for storage, which allows you to manage your saved layouts, see a history of your changes (on the GitHub website), "star" your favorite layouts, fork layouts created by other people, etc.

There are still a few rough edges, but it turned out pretty good and didn't take very long to implement.  Anyway... you should now have roughly 1MB of space for each layout.  :)

I want to enhance it further (e.g., see your layout history directly within the site), but let me know if you have any enhancement ideas, and definitely log any bugs you find!

**Comment by jasonm23** [comment]
Awesome, this is where I store my layouts until I turn them into full repos
