### ISSUE TITLE
Mac Keyboards

### ISSUE THREAD

**Issue by alistaircom** [ijprest/keyboard-layout-editor#128]
Created a couple keyboards that you're welcome to add to your presets if you like:

* Apple wireless keyboard: http://www.keyboard-layout-editor.com/#/gists/4a3250ac7fcee88166da
* MacBook keyboard: http://www.keyboard-layout-editor.com/#/gists/3857f00121d0604f0624

**Comment by iandoug** [comment]
Ah cool you designed chicklet keys ... very nice.

**Comment by ijprest** [comment]
Looks pretty good!  

I think I'll eventually need to do a proper "profile" for chicklet keys, though, since this technique relies on artificially spacing the keys out.  I'm not sure how much time I'll have this weekend (family obligations), but I'll try to whip something up.

**Comment by iandoug** [comment]
I'm also busy with something but not in that direction :-)

A while back I saw a keypad, I think for iPads, that was made of bamboo .. bamboo case and bamboo chicklet keys.

Which is why I suggested way back when we did the backgrounds, that we may need to use the same textures on the keys. Chicklets will probably be much easier than regular keys in that regard .. especially since Angular does not appear able to 'stack' backgrounds (yet?), and you'll probably need a transparency mask over parts of the keys to get the 3D effect...

**Comment by alistaircom** [comment]
Sounds great either way. 

I had a great time working with the editor and ended up getting really detailed with making it look as close to my keyboards as possible.

**Comment by ijprest** [comment]
OK, I've added a 'CHICKLET' profile.  The CHICKLET profile allows easier placement of the keys (since the inter-key spacing is built-in).

I also added your Apple Wireless sample to the samples list.  I tweaked it to use the new profile, and also changed it to use a look-alike font that I licensed (to make the rendering as realistic as possible).

See 65947be7b8257d3370b47fb6718263dd36784d72 and 2b13f0c3e278313b8d4bf2a0db4a233fbefb4a1a.

Should be live now, but you may need to force a refresh.

**Comment by iandoug** [comment]
Nice job on that curve at the top... :-) looks almost like the photo at http://media.engadget.com/img/product/3/2ov/wireless-keyboard-2nd-gen-21do-800.jpg
