### ISSUE TITLE
Improved movement for groups of selected keys

### ISSUE THREAD

**Issue by tylert** [ijprest/keyboard-layout-editor#140]
It is nice and easy to select multiple keys in the current version of the tool.  However, if you try to select a bunch of keys and then increment/decrement the X or Y values, all keys in the group immediately get the *same* X or Y values rather than having their individual values incremented/decremented.

It would be nice to be able to easily perform something similar to the following:
- use an existing template
- select all keys and move them 1.0 units to the right
- add a new column of 1.0 unit keys to the left-hand side

Likewise, another use case might be:
- use an existing template
- select the top row of F-keys and delete them
- select all remaining keys and move them 1.5 units up

**Comment by tylert** [comment]
There is perhaps also an argument to made that this more like a "bug" in the current movement tools rather than a feature request.

**Comment by iandoug** [comment]
Are you moving them by typing in values, or using the cursor keys? For example, your second use case works fine with the cursor keys for me.

**Comment by tylert** [comment]
Oh... I never tried using keyboard shortcuts to move them.  I was actually clicking with the mouse on the little up/down arrows next to the X/Y text input boxes.

PEBKAC only or should it grey out the text input field increment/decrement buttons or something when selecting multiple keys?

**Comment by tylert** [comment]
Yes, moving selected keys around with they arrow keys on the keyboard works fine, however, clicking the increment/decrement buttons next the X/Y text field will still collapse the group of keys you're trying to move.

**Comment by iandoug** [comment]
That's probably an undesired consequence of the design decision to minimise the size of the .json file by letting succeeding keys inherit values from the previous key, instead of explicitly setting every value for every key. (I'm speaking out of turn for IJP here, under correction). The same sort of thing pops up when you adjust the text size of a key that inherited its size... instead of just incrementing, it starts counting at size 1. AFAICS the only fix will be to specify all values for every key, but that raises other issues, for example moving keys will then involve manually updating each key's xy, instead of just the first one, and basing the other positions off that. Or perhaps there is a compromise middle ground.

Speaking of moving using the cursor keys, I trust you discovered the Settings dialogue on the right which allows you adjust how much the keys move :-)
