### ISSUE TITLE
Some fontawesome icons missing?

### ISSUE THREAD

**Issue by iandoug** [ijprest/keyboard-layout-editor#144]

**Comment by iandoug** [comment]
For example, fa-rebel ?

**Comment by iandoug** [comment]
"name": "font-awesome",
  "description": "Font Awesome",
  "version": "4.3.0",

So how do we persuade bower to get 4.4.0?
"bower update" still pulls 4.3,

**Comment by ijprest** [comment]
Fixed by 50347112a6e096e7aa6d37757b118b9b75e27859.  Also updated to FA 4.4.0.

The problem was in parsing the CSS file; I was ignoring any rule where multiple selectors were present.  So since, e.g., "rebel" had an alias, its rule was written as ```.fa-rebel:before, .fa-ra:before { ... }``` and I was ignoring it.  Now I loop over all of the selectors.

FYI: There are lots of ways to do update bower packages, but I find the easiest way to do it is to edit ```./bower.json```, change the version number for the package you want to update, and then run ```bower update```.
