### ISSUE TITLE
signing in with github leaves the save button disabled

### ISSUE THREAD

**Issue by guest20** [ijprest/keyboard-layout-editor#147]
Steps to reproduce:

* change the layout
* click sign in
* grant permission
* watch your username appear at the top, but the save button stay disabled

You still can't save, but now you're logged in.

**Comment by ijprest** [comment]
Unless I'm misinterpreting your comments, this is by design.  

The 'save' button is only enabled if the layout is 'dirty' (i.e., changed since last save).  Since you haven't modified anything since loading a preset, there's no reason to save it.  If you change the layout in any way (move a key, change legends/colors, etc.), the save button should get enabled.

**Comment by guest20** [comment]
You have mis-understood, step 1 is "change the layout" ... as in, make any edit at all.

Additionally, Does it even make sense to not just let a user save whenever they like?
i could sign in and want to add something that is unsaved, but clean to my account (given that you can't ever save whens signed out).

**Comment by ijprest** [comment]
Hrm... then I'm unable to reproduce this.

Questions:  
* Does it happen every time?
* Do subsequent changes enable the save button?  
* Is the "Undo" button enabled?
* Does it matter what type of change you make?

**Comment by guest20** [comment]
I can't reproduce it now.

it did it a second time when I commented on the ticket, but not now ... either you did a sneaky release or my browser is caching silly things?

Oh well, never mind.
