### ISSUE TITLE
Need support for negative values for X and Y positions

### ISSUE THREAD

**Issue by vladresende** [ijprest/keyboard-layout-editor#178]
When used high values for rotation, the keys got too far in the midle (or outside) the KB. It would be solved with the possbility to give negative entries for X and Y values.

**Comment by leobrowning92** [comment]
I agree, the issue seems to be with how key rotation is handled. it seems to rotate the reference frame, so that the "top" is rotated as well. Since I imagine that the function of only +ve values of x and y is to keep keys in a viable workspace, the issue might be better approached by changing how the rotation is handled.

**Comment by leobrowning92** [comment]
After some more playing around the specific issue, that rotated keys have some limits on their position, can be overcome by moving the center of rotation for that key using `ctrl+arrows`.

**Comment by vladresende** [comment]
This might work, thanks!
