### ISSUE TITLE
PNG output & JPG output do not work when DCS or OEM profile are specified

### ISSUE THREAD

**Issue by thjwong** [ijprest/keyboard-layout-editor#198]
PNG output & JPG output do not work when DCS or OEM profile are specified, however, SVG output will still work.

There is no problem of PNG & JPG output when SA, DSA, or CHICKLET are specified.

When I remove the DCS specification of key profile, the default looks kind of like DCS, and there is no problem of PNG & JPG output with that.

**Comment by iandoug** [comment]
PNG and JPG output basically grab an image out of memory (off the canvas). I'm not sure why the type of keycap profile would affect that. I will take a look. Which OS and browser are you using?

**Comment by ijprest** [comment]
Hrm... I can't reproduce it here on the current versions of Chrome & FF.  I just tried the "GB: CCnG" preset, which uses DCS, and downloading a PNG worked as expected: colors, text, gradients, etc., all looked correct.

Since this is pretty old, I'm going to close it as "No Repro" unless & until we get more details.
