### ISSUE TITLE
How exactly do you use the .json?

### ISSUE THREAD

**Issue by nathgit** [ijprest/keyboard-layout-editor#240]
Can you use it to create a custom keyboard (input method)? I have an extension that adds an esperanto keyboard. The extension is just a json. Is it possible to do that with the .json generated with this? I'm using Chrome OS.

**Comment by ijprest** [comment]
Short answer: No.

Long answer:  The JSON describes is just an alternative way to save or backup your data (e.g., if you didn't want to log-in and save it on GitHub).  It describes the *physical* layout of the keyboard, and the physical properties of the keys/caps.

There are also a few unaffiliated third-party sites that can take the JSON (or raw data) and do things with them, e.g., [Swill's plate builder](http://builder.swillkb.com/).

While I suppose it would be *possible* for a third-party site to do something to map the keycap-legends to scancodes, etc., in order to generate something that ChromeOS can consume, I don't actually know of any sites or tools that have attempted this.  It's not really what KLE was designed for, so it would be kind of a hack.
