### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by ellisgl** [ijprest/keyboard-layout-editor#276]
I noticed there hasn't been any merges in a long time and @ijprest last commit to anything was back in December and the one before was a long time before that.

**Comment by alerque** [comment]
See #218. The owner isn't dead (so that's good) and there is _some_ motion on his implementation ideas, but since he doesn't want to fully open source the current state of the project either it's basically blocked by the original author. There can't really be any significant progress from the community side because of that impasse.

**Comment by ellisgl** [comment]
I started work on a better schema, but with life I have little time to finish and polish it, so it's a slow going processes. So if anyone wants to help contribute, that would be great. https://github.com/ellisgl/keyboard-schema
Pretty much all the stuff I do on GitHub is under  BSD license.

**Comment by ellisgl** [comment]
I've decided to continue on the schema (in TypeScript). Maybe it end up being use in an alternative app.
