### ISSUE TITLE
Raw data as JSON

### ISSUE THREAD

**Issue by doub** [ijprest/keyboard-layout-editor#55]
It would be nice if the raw data could be formated as a correct and complete JSON document instead of raw partial Javascript array definition. This would make the data easier to parse from other tools and scripts.

**Comment by iandoug** [comment]
A bit clunky but I'm using this to fix:
<?php
  $fp = fopen ("input.txt", "r"); # file with the code
  
  $outfp = fopen ("output.json", "w");
  fwrite ($outfp, "[\n");

  while ($s = fgets ($fp, 4096))
   { 

      $s = preg_replace('/y:/', '"y":', $s);
      $s = preg_replace('/x:/', '"x":', $s);
      $s = preg_replace('/c:/', '"c":', $s);
      $s = preg_replace('/f:/', '"f":', $s);
      $s = preg_replace('/f2:/', '"f2":', $s);
      $s = preg_replace('/r:/', '"r":', $s);
      $s = preg_replace('/rx:/', '"rx":', $s);
      $s = preg_replace('/ry:/', '"ry":', $s);
      $s = preg_replace('/w:/', '"w":', $s);
      $s = preg_replace('/h:/', '"h":', $s);
      $s = preg_replace('/a:/', '"a":', $s);
      fwrite ($outfp, $s);
   };
  fwrite ($outfp, "]\n");
?>

**Comment by D1SC0tech** [comment]
Awesome, where did you stick that code?

**Comment by iandoug** [comment]
It's a little stand-alone program.

There appears to be a bug in KLE when dealing with rotated key blocks, and the rx and ry (rotation origins) gets lost from the source code view. So at present I am running the KLE locally, and editing my source code in an editor, then loading it as a preset.

**Comment by D1SC0tech** [comment]
Ah, okay. Right now I'm trying to fix the quotes problem by modifying jsonl.grammar.js

**Comment by iandoug** [comment]
That's a much better solution :-)

I confess to being lost in his code. I have done some JQuery, but no FontAwesome stuff or Angular stuff, and only recently (as in this month) started producing Json outputs.

There is already a fork/enhancement of the system here: 
https://github.com/amj/keyboard-layout-editor
But the new features are not working in my browser (FF on linux). However I am using this fork locally. 

Have you been able to get hold of the original author so we can get clarity on the legal postion about fixes/updates?

Thanks.

**Comment by D1SC0tech** [comment]
I'm actually a self-taught coder (my major is EE, not CS), so I'm definitely struggling with this. I've also never worked with JQuery, FontAwesome, or Angular.

Oh man, that fork looks awesome! I might pull some of his stuff in to [mine](https://github.com/D1SC0tech/keyboard-layout-editor).

I seem to remember trying to contact him about handing over ownership to the community, but I don't think he responded. I'm trying to get a fork up-and-running on an actual server, so this is kinda important. If you want to help with my fork, let me know and I can give you my email.

**Comment by D1SC0tech** [comment]
Also, I currently have my fork running a gh-pages branch at http://d1sc0tech.github.io/keyboard-layout-editor/. It doesn't seem my 'fix' worked...

**Comment by iandoug** [comment]
Impressive to-do list which has some of the items on mine. I was not ambitious enough to attempt integrating the plate builder, I thought I could maybe just pass the data through to him.
My current list looks like this:
ToDo: 
1. fix save to include rx ry rotation origin.
2. get stepsize working (ie make the moving a variable instead of 0.25 keysize)
3. get anglestep working (likewise, instead of 15 degrees)
4. specify font + size per text entry
5. include other useful fonts, with Character Picker.
6. get svg save working (not working for me ATM)
7. LEDs
8. Branding
9. svg to jpg/png via inkscape
10. holes (as per other fork)
11. keys (ditto)
12. link to generate cutouts.

I'm very tied up this month, (and in truth this is keeping me away from important work) but next month should be better.

**Comment by iandoug** [comment]
Can't find place to comment on your fork, where did you get engravers_gothic_fsregular from? I tried to find it but it appears to be commercial. I did find a 'free' version but not sure if it is actually free or just an uploaded or website claiming so.

**Comment by D1SC0tech** [comment]
There is absolutely nothing on your TODO that I disagree with. This is going to be a lot of work... :grimacing: 

As for the font, I just replaced `font-family: 'engravers_gothic_fsregular';` with `font-family: 'engravers_gothic_fsregular', "Arial", "Helvetica", sans-serif;`. Since Engravers' Gothic is proprietary, it falls back to Arial, which looks a bit weird but is fine for now. Getting custom font support is a must.

**Comment by iandoug** [comment]
I see on your live site that your samples don't load. Remove the leading / in layouts.json, eg
/samples/gb-ccng should be
samples/gb-ccng

**Comment by D1SC0tech** [comment]
I can't believe I didn't catch that...fixed.
Thanks!

**Comment by iandoug** [comment]
See https://github.com/ijprest/keyboard-layout-editor/wiki/Serialized-Data-Format
I need to add a few more to my code.

**Comment by iandoug** [comment]
Curious. I loaded my local version in Chrome, my presets are all broken, as are the swatches (I upgraded the AngularJS and FontAwesome stuff to current versions), but the SVG function works.
So clearly there is something unstable in the code that some things work in FF and not in Chrome, and vice-versa.

**Comment by iandoug** [comment]
Mmm I see you have switched "Samples" to "Keysets". I should have checked what you had done :-)
I've refactored the layouts so that each layout is in a separate file, in either "preset" or "samples" directory. This required editing layouts.json and some changes to kb.js. I've also integrated a bunch of other layouts from your version and the other fork plus some given in the 'issues' here as not working in Firefox (they do now). Now what? :-) I'm not up to speed with Git. :-)

**Comment by D1SC0tech** [comment]
I just opened a [new issue](https://github.com/D1SC0tech/keyboard-layout-editor/issues/5) on my fork so we can stop clogging up this issue.

**Comment by ijprest** [comment]
This wasn't publicized, but you could always get the raw/strict JSON by saving your layout (they're stored on the server in raw/strict form)... you just needed a small tweak to your your "saved" URL.  Remove the extra "/#" in the middle of the URL, and you would end up downloading the raw JSON.

Regardless, as per #56, you can now download (and upload) the raw data in "strict" JSON format.
