### ISSUE TITLE
Per-legend coloring

### ISSUE THREAD

**Issue by p3lim** [ijprest/keyboard-layout-editor#59]
I'd like to do coloring on a per-legend or per-legend-slot basis, so that we could color the fn layer legends or accents, like this:

https://flic.kr/p/ng7e3a

Other than improving the vision of a finished product, it also helps when this tool is used to explain a layout, especially for people less aware of layers and their function.

**Comment by ijprest** [comment]
Implemented in 5b063b9b5e2a265aa9a890f16994dc3900fd1498.

* There is now a color picker beside each label edit-box.  You can click on this to enter/pick a color.
* You can also drag/drop from one of the palettes to the label edit-boxes to use one of the palette colors.
* The first label/color is the primary one; it's color is used for all labels that have not *overridden* the color.  (The UI might be a bit confusing, since it doesn't actually tell you which ones are overridden.)
* You can blow away all overrides by using the old "label color" field at the bottom of the form.
