### ISSUE TITLE
Double angle bracket '<' breaks all label input fields

### ISSUE THREAD

**Issue by thepiper** [ijprest/keyboard-layout-editor#65]
Inputting "<<" into any label field breaks editing that particular key - neither positioning or size changes take effect. Multiple selection affected as well

Have not tested if it breaks anything else.

**Comment by ijprest** [comment]
The input fields allow HTML tags & entities, and in this case, there was an exception being thrown while parsing the HTML (since '<<' isn't really valid HTML).  Updating to the latest version of Angular 1.2 (863ae49c3a24c3520c1287b234392f94819c03e0) seems to fix this specific issue case... it's smart enough to recognize '<<' for what you intended.  

However, I am now also catching the exception and replacing the label with an error glyph (with a tooltip) in cases where the label is still problematic (4e5f2e66a1532127011f34ef65469d0f0188512c).  This prevents the editor from exhibiting the bad behaviour you were seeing (not rendering properly, selection problems, etc.).
